apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tyger.fullname" . }}-storage
spec:
  selector:
    matchLabels:
      component: {{ include "tyger.fullname" . }}-storage
  replicas: 1
  template:
    metadata:
      labels:
        component: {{ include "tyger.fullname" . }}-storage
    spec:
      initContainers:
        - name: check-db-ready
          image: jbergknoff/postgresql-client
          command:
            - 'sh'
            - '-c'
            - |
              until pg_isready -U {{ template "postgresql.username" .Subcharts.storagedb }} -d {{ .Values.storagedb.postgresqlDatabase }} -h {{ template "common.names.fullname" .Subcharts.storagedb }} -p 5432; do
                echo waiting for database
                sleep 2
              done
        {{- if .Values.storageEmulator.enabled }}
        - name: check-azurite-ready
          image: yauritux/busybox-curl
          command:
            - 'sh'
            - '-c'
            - |
              until curl http://devstoreaccount1.{{ .Release.Namespace }}:10000/; do
                echo waiting for azurite
                sleep 2
              done
        {{- end }}
      containers:
        - name: mrd-storage-server
          image: {{ .Values.storageServer.image }}
          env:
            - name: MRD_STORAGE_SERVER_DATABASE_PROVIDER
              value: postgresql
            - name: MRD_STORAGE_SERVER_DATABASE_CONNECTION_STRING
              value: host={{ template "common.names.fullname" .Subcharts.storagedb }} dbname={{ .Values.storagedb.postgresqlDatabase }} port=5432 user={{ template "postgresql.username" .Subcharts.storagedb }}
            - name: MRD_STORAGE_SERVER_DATABASE_PASSWORD_FILE
              value: /etc/secrets/postgresql-password
            - name: MRD_STORAGE_SERVER_STORAGE_PROVIDER
              value: azureblob
            - name: MRD_STORAGE_SERVER_STORAGE_CONNECTION_STRING_FILE
              value: /etc/secrets/storage-connection-string
          volumeMounts:
          - name: secrets
            mountPath: /etc/secrets
            readOnly: true
      volumes:
      - name: secrets
        projected:
          sources:
          - secret:
              name: {{ template "common.names.fullname" .Subcharts.storagedb  }}
          - secret:
              {{- if .Values.storageEmulator.enabled }}
              name: {{ include "tyger.fullname" . }}-azurite-connection-string
              items:
                - key: connectionString
              {{- else }}
              name: {{ required "A value for storagedb.storageAccountConnectionStringSecretName" .Values.storageServer.storageAccountConnectionStringSecretName }}
              items:
                - key: {{ .Values.storageServer.storageAccountConnectionStringSecretDataKey }}
              {{- end }}
                  path: storage-connection-string
---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "tyger.fullname" . }}-storage
spec:
  selector:
    component: {{ include "tyger.fullname" . }}-storage
  ports:
    - name: storage
      protocol: TCP
      port: 8080
      targetPort: 3333
