# Trigger on changes to the "main" branch
trigger:
- main

# Trigger for PRs that target the "main" branch
pr:
- main

pool: tyger

variables:
  DOCKER_BUILDKIT: 1
  IS_PR: $[ne(variables['System.PullRequest.PullRequestId'], '')]
  IS_CI: $[or(eq(variables['Build.Reason'], 'IndividualCI'), eq(variables['Build.Reason'], 'BatchedCI'))]

  DEVCONTAINER_IMAGE: compimagdevcontainers.azurecr.io/tyger@sha256:db18c3712de8c8c95d9618a8868a9e80e3dd3adc4d57520c89a86deb444609a1

jobs:
- job: buildAndTest
  displayName: "Deploy and run tests"
  timeoutInMinutes: 90
  container:
    image: $(DEVCONTAINER_IMAGE)
  variables:
    BASH_ENV: /opt/devcontainer/devcontainer.bashrc
    TYGER_ENVIRONMENT_CONFIG_DIR: $(Build.SourcesDirectory)/deploy/config/dev/ci # Disable scale-to-zero
    ENVIRONMENT_PROVISIONED: false

  steps:

  - script: |
      set -euo pipefail

      if [[ "$(.devcontainer/get-devcontainer-image.sh)" != "${DEVCONTAINER_IMAGE}" ]]; then
        echo "The devcontainer image in azure-pipelines.yml and devcontainer.json must be the same"
      fi

      docker build -f .devcontainer/Dockerfile --target devcontainer -t devcontainer --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ${DEVCONTAINER_IMAGE} .

      if ! .devcontainer/diff-container-images.sh "${DEVCONTAINER_IMAGE}" devcontainer; then
        echo 'Error: the "image" field in devcontainer.json does not reflect the current "devcontainer" target of the Dockerfile. Run .devcontainer/update-devcontainer-image.sh to correct this.'
        exit 1
      fi
    displayName: Verify devcontainer.json

  - script: |
      make restore
      make verify-format
    displayName: "Build and verify formatting"

  - script: |
      # The AzureCLI@2 task needs to be able to execute the az command in the container, before running
      # our script, without activating the conda environment
      echo '##vso[task.prependpath]/opt/conda/envs/tyger/bin'

      # Determine the envionment name to use
      if [[ "${IS_PR}" == "True" ]]; then
        environment_name="tyger-pr${SYSTEM_PULLREQUEST_PULLREQUESTID}"
      else
        environment_name="tygerwestus2"
      fi

      echo "##vso[task.setvariable variable=TYGER_ENVIRONMENT_NAME]${environment_name}"

      env | sort

    displayName: Set variables

  - task: AzureCLI@2
    displayName: Ensure environment
    inputs:
      azureSubscription: BiomedicalImaging-NonProd
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        make ensure-environment
        echo "##vso[task.setvariable variable=ENVIRONMENT_PROVISIONED;]true"

  - task: AzureCLI@2
    displayName: Deploy code and run tests
    inputs:
      azureSubscription: BiomedicalImaging-NonProd
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -euo pipefail

        # Allow repo to be properly bind mounted in test container
        export CONTAINER_WORKSPACE_DIR=$(pwd)
        export HOST_WORKSPACE_DIR=$(.devcontainer/get-host-workspace-directory.sh)

        make

  - task: AzureCLI@2
    condition: always()
    displayName: Cleanup
    inputs:
      azureSubscription: BiomedicalImaging-NonProd
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -euo pipefail

        # Point to scale-to-zero config
        export TYGER_ENVIRONMENT_CONFIG_DIR="${BUILD_SOURCESDIRECTORY}/deploy/config/dev/"

        if [[ "${AGENT_JOBSTATUS}" == "Succeeded" ]]; then
          if [[ "${IS_PR}" == "True" ]]; then
            echo "deleting environment"
            make remove-environment
            exit
          fi

          echo "scaling cluster back down"
          make ensure-environment
          exit
        fi

        if [[ $"ENVIRONMENT_PROVISIONED" == "false" ]]; then
          echo "leaving environment as-is"
          exit
        fi

        echo "scaling cluster back down"
        make ensure-environment
