# Trigger on changes to the "main" branch
trigger:
- main

# Trigger for PRs that target the "main" branch
pr:
- main

variables:
  DOCKER_BUILDKIT: 1
  IS_PR: $[ne(variables['System.PullRequest.PullRequestId'], '')]
  IS_CI: $[or(eq(variables['Build.Reason'], 'IndividualCI'), eq(variables['Build.Reason'], 'BatchedCI'))]

  DEVCONTAINER_IMAGE: compimagdevcontainers.azurecr.io/tyger@sha256:4daae2c3bea06bb309ccbc378ed461a6a03e9bc1013683eecec5d67b7cf66b60

jobs:
- job: buildAndTest
  displayName: "Deploy and run tests"
  timeoutInMinutes: 90
  pool: tyger
  container:
    image: $(DEVCONTAINER_IMAGE)
  variables:
    BASH_ENV: /opt/devcontainer/devcontainer.bashrc
    TYGER_ENVIRONMENT_CONFIG_DIR: $(Build.SourcesDirectory)/deploy/config/dev/ci # Disable scale-to-zero

  steps:

  - script: |
      # add the current user to the conda group
      sudo usermod -aG conda $(whoami)
      
      # The AzureCLI@2 task needs to be able to execute the az command in the container, before running
      # our script, without activating the conda environment
      echo '##vso[task.prependpath]/opt/conda/envs/tyger/bin'

      # Determine the envionment name to use
      if [[ "${IS_PR}" == "True" ]]; then
        environment_name="tyger-pr${SYSTEM_PULLREQUEST_PULLREQUESTID}"
      else
        environment_name="tygerwestus2"
      fi

      echo "##vso[task.setvariable variable=TYGER_ENVIRONMENT_NAME]${environment_name}"
      tyger_uri=$(TYGER_ENVIRONMENT_NAME="${environment_name}" make -s get-tyger-uri)
      echo "##vso[task.setvariable variable=TYGER_URI;isOutput=true]${tyger_uri}"

    name: setVariables
    displayName: Set variables

  - script: |
      set -euo pipefail

      if [[ "$(.devcontainer/get-devcontainer-image.sh)" != "${DEVCONTAINER_IMAGE}" ]]; then
        echo "The devcontainer image in azure-pipelines.yml and devcontainer.json must be the same"
      fi

      docker build -f .devcontainer/Dockerfile --target devcontainer -t devcontainer --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ${DEVCONTAINER_IMAGE} .

      if ! .devcontainer/diff-container-images.sh "${DEVCONTAINER_IMAGE}" devcontainer; then
        echo 'Error: the "image" field in devcontainer.json does not reflect the current "devcontainer" target of the Dockerfile. Run .devcontainer/update-devcontainer-image.sh to correct this.'
        exit 1
      fi
    displayName: Verify devcontainer.json

  - script: |
      make restore
      make verify-format
    displayName: "Build and verify formatting"

  - task: AzureCLI@2
    displayName: Deploy and run tests
    inputs:
      azureSubscription: BiomedicalImaging-NonProd
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -euo pipefail
        make -s -j 8

  - script: |
      set -euo pipefail

      export CGO_ENABLED=1 
      export GOOS=windows
      export GOARCH=amd64
      
      cd cli
      go build -ldflags="-s -w" -v -o $(Build.ArtifactStagingDirectory)/windows-cli-tools/tyger.exe ./cmd/tyger
      go build -ldflags="-s -w" -v -o $(Build.ArtifactStagingDirectory)/windows-cli-tools/tyger-proxy.exe ./cmd/tyger-proxy
    displayName: Build Windows binaries

  - publish: '$(Build.ArtifactStagingDirectory)/windows-cli-tools'
    displayName: Publish Windows binaries
    artifact: windowsCliTools

  - task: AzureCLI@2
    condition: and(succeeded(), eq(variables.IS_CI, 'true'))
    displayName: Push Images
    inputs:
      azureSubscription: BiomedicalImaging-NonProd
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        make publish-cli-tools-image

  - task: AzureCLI@2
    condition: always()
    displayName: Cleanup
    inputs:
      azureSubscription: BiomedicalImaging-NonProd
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -euo pipefail

        # Point to scale-to-zero config
        export TYGER_ENVIRONMENT_CONFIG_DIR="${BUILD_SOURCESDIRECTORY}/deploy/config/dev/"

        echo "scaling cluster back down"
        make ensure-environment

- job: windowsSmokeTests
  displayName: 'Run Windows smoke tests'
  dependsOn: buildAndTest
  pool:
    vmImage: 'windows-latest'
  variables:
    GOBIN: $(Agent.TempDirectory)\bin
    TYGER_URI: $[ dependencies.buildAndTest.outputs['setVariables.TYGER_URI'] ]
    CLI_TOOLS_IMAGE: $[ dependencies.buildAndTest.outputs['publishCliTools.CLI_TOOLS_IMAGE'] ]

  steps:

    - download: current
      artifact: windowsCliTools

    - task: AzureCLI@2
      displayName: Run certificate tests
      inputs:
        azureSubscription: BiomedicalImaging-NonProd
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          $env:PATH = "$(Pipeline.Workspace)\windowsCliTools;"+ $env:PATH

          # Run tests
          .\scripts\Test-CertificateLoginOnWindows.ps1 -ServerUri $env:TYGER_URI
