openapi: "3.1.0"
info:
  version: 1.0.0-alpha
  title: Tyger
  description: Control plane for cloud-based signal processing.
paths:
  /v1/buffers:
    post:
      summary: Creates a new buffer.
      description: Creates a new buffer
      operationId: createBuffer
      requestBody:
        content:
          application/json: {}
      responses:
        '201':
          description: buffer response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Buffer'
          headers:
            Location:
              schema:
                type: string
                format: uri
              description: The URI where the buffer's metadata can be retrieved
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v1/buffers/{id}:
    get:
      summary: Returns a buffer by ID
      description: Returns a buffer based on a its ID
      operationId: getBufferByID
      parameters:
        - name: id
          in: path
          description: ID of the buffer to fetch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: buffer response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Buffer'
        '404':
          description: The buffer was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v1/buffers/{id}/access:
    post:
      summary: Obtains a time-bound URI that allows read and optionally write access to the buffer
      description: Obtain a URI that allows read and optionally write access to the buffer
      operationId: getBufferAccessUri
      parameters:
        - name: id
          in: path
          description: ID of the buffer
          required: true
          schema:
            type: string
        - name: writeable
          in: query
          description: Whether the URI should grant write access to the buffer
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '201':
          description: Access URI response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BufferAccess'
        '404':
          description: The buffer was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/codespecs/{name}:
    put:
      summary: Create or update a codespec
      description: Create or update a codespec
      operationId: upsertCodespec
      parameters:
        - name: name
          in: path
          description: The name of the codespec
          required: true
          schema:
            type: string
      requestBody:
        description: The codespec specification
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Codespec'
      responses:
        '201':
          description: The codespec was created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Codespec'
          headers:
            Location:
              schema:
                type: string
                format: uri
              description: The versioned URI to the codespec.
        '200':
          description: The codespec was updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Codespec'
          headers:
            Location:
              schema:
                type: string
                format: uri
              description: The versioned URI to the codespec.
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      summary: Get the latest version of a codespec
      description: Get the latest version of a codespec
      operationId: getLatestCodespec
      parameters:
        - name: name
          in: path
          description: The name of the codespec
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The latest codespec
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Codespec'
          headers:
            Location:
              schema:
                type: string
                format: uri
              description: The versioned URI to the codespec.
        '404':
          description: The codespec was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/codespecs/{name}/versions/{version}:
    get:
      summary: Get a specific version of a codespec
      description: Get a specific version of a codespec
      operationId: getCodespecVersion
      parameters:
        - name: name
          in: path
          description: The name of the codespec
          required: true
          schema:
            type: string
        - name: version
          in: path
          description: The codespec version
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The codespec
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Codespec'
        '404':
          description: The codespec was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/runs:
    post:
      summary: Creates and starts a new run.
      description: Creates and starts a new run.
      operationId: createRun
      requestBody:
        description: The run specification
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewRun'
      responses:
        '201':
          description: run response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Run'
          headers:
            Location:
              schema:
                type: string
                format: uri
              description: The URI where the run's metadata can be retrieved
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/runs/{id}:
    get:
      summary: Get run
      description: Gets the status of a run
      operationId: getRun
      parameters:
        - name: id
          in: path
          description: The run ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: run response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Run'
        '404':
          description: The run was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Buffer:
      required:
        - id
      properties:
        id:
          type: string
          description: The buffer ID

    BufferAccess:
      required:
        - uri
      properties:
        uri:
          type: string
          format: uri
          description: The URI to read or write to the buffer

    BufferParameters:
      properties:
        inputs:
          type: array
          items:
            type: string
        outputs:
          type: array
          items:
            type: string

    Codespec:
      required:
        - image
      properties:
        buffers:
          $ref: '#/components/schemas/BufferParameters'
        image:
          type: string
          description: The container image to run
        command:
          type: array
          items:
            type: string
        args:
          type: array
          items:
            type: string
        env:
          type: object
          additionalProperties:
            type: string

    NewRun:
      required:
        - codespec
      properties:
        codespec:
          type: string
          description: A reference to an existing codespec. Can be of the form "mycodespec" or "mycodespec/versions/6"
        buffers:
          type: object
          additionalProperties:
            type: string
          description: |
            The buffers used in this reconstruction, specified as a mapping from name to id.

    Run:
      allOf:
        - required:
            - id
          properties:
            id:
              type: string
              description: The run ID.
            status:
              type: string
              description: The status od the run.
        - $ref: '#/components/schemas/NewRun'

    Error:
      required:
        - error
      properties:
        error:
          $ref: '#/components/schemas/ErrorInfo'

    ErrorInfo:
      required:
        - code
        - message
      properties:
        code:
          type: string
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
