tyger:
  job:
    image: eminence.azurecr.io/recon:current
    replicas: 1
    input:
      - "input"
    output:
      - "output"
    command: []
    args:
      - "-i"
      - "$(INPUT_PIPE)"
      - "-o"
      - "$(OUTPUT_PIPE)"
    resources:
      requests:
        cpu: 1
