tyger:
  job:
    image: eminencepublic.azurecr.io/gadgetron:current
    replicas: 1
    input:
      - "input"
    output:
      - "output"
    command: []
    args:
      - "-c"
      - "CMR_2DT_RTCine_KspaceBinning_Cloud.xml"
      - "--from_stream"
      - "-i"
      - "$(INPUT_PIPE)"
      - "-o"
      - "$(OUTPUT_PIPE)"
      - "--storage_address"
      - "$(MRD_STORAGE_URI)"
    nodepool: cpunp
    env:
      GADGETRON_REMOTE_WORKER_COMMAND: printenv TYGER_GADGETRON_WORKER_ENDPOINT_ADDRESSES
    resources:
      requests:
        cpu: 1
  worker:
    image: eminencepublic.azurecr.io/gadgetron:current
    replicas: 2
    nodepool: cpunp
    args: ["--storage_address", "$(MRD_STORAGE_URI)"]
    endpoints:
      gadgetron: 9002
    resources:
      requests:
        cpu: 3000m
        memory: 4G
      limits:
        memory: 4G
