tyger:
  job:
    image: eminence.azurecr.io/gadgetron_recon:latest
    replicas: 1
    input:
      - "input"
    output:
      - "output"
    command: []
    args:
      - "-c"
      - "default.xml"
      - "-r"
      - "$(INPUT_BUFFER_URI_FILE)"
      - "-w"
      - "$(OUTPUT_BUFFER_URI_FILE)"
    resources:
      memory: 1G
