tyger:
  job:
    image: eminencepublic.azurecr.io/gadgetron:current
    replicas: 1
    input:
      - "input"
    output:
      - "output"
    command: []
    args:
      - "-c"
      - "Generic_Cartesian_FFT.xml"
      - "--from_stream"
      - "-i"
      - "$(INPUT_PIPE)"
      - "-o"
      - "$(OUTPUT_PIPE)"
      - "--storage_address"
      - "$(MRD_STORAGE_URI)"
    resources:
      requests:
        cpu: 1
