job:
  codespec:
    image: eminence.azurecr.io/recon:current
    buffers:
      inputs:
        - input
        - noisecovariance
      outputs:
        - output
    args:
      - "-i"
      - "$(INPUT_PIPE)"
      - "-o"
      - "$(OUTPUT_PIPE)"
      - "-n"
      - "$(NOISECOVARIANCE_PIPE)"
    resources:
      requests:
        cpu: 1
