job:
  codespec:
    image: eminence.azurecr.io/recon:current
    buffers:
      inputs:
        - input
      outputs:
        - output
        - noisecovariance
    args:
      - "-p"
      - "noise"
      - "-i"
      - "$(INPUT_PIPE)"
      - "-o"
      - "$(OUTPUT_PIPE)"
      - "-n"
      - "$(NOISECOVARIANCE_PIPE)"
    resources:
      requests:
        cpu: 1
