job:
  codespec:
    image: eminencepublic.azurecr.io/gadgetron:current
    buffers:
      inputs:
        - input
      outputs:
        - output
    args:
      - "-c"
      - "CMR_2DT_RTCine_KspaceBinning_Cloud.xml"
      - "--from_stream"
      - "-i"
      - "$(INPUT_PIPE)"
      - "-o"
      - "$(OUTPUT_PIPE)"
    env:
      GADGETRON_REMOTE_WORKER_COMMAND: printenv TYGER_GADGETRON_WORKER_ENDPOINT_ADDRESSES
    resources:
      requests:
        cpu: 1
  nodePool: cpunp

worker:
  codespec:
    image: eminencepublic.azurecr.io/gadgetron:current
    args: []
    endpoints:
      gadgetron: 9002
    resources:
      requests:
        cpu: 3000m
        memory: 4G
      limits:
        memory: 4G
  replicas: 2
  nodePool: cpunp
