job:
  codespec:
    image: eminencepublic.azurecr.io/gadgetron:current
    buffers:
      inputs:
        - input
      outputs:
        - output
        - noisecovariance
    args:
      - "-c"
      - "default_measurement_dependencies.xml"
      - "--from_stream"
      - "-i"
      - "$(INPUT_PIPE)"
      - "-o"
      - "$(OUTPUT_PIPE)"
      - --disable_storage
      - 'true'
      - --parameter
      - noisecovarianceout=$(NOISECOVARIANCE_PIPE)
    resources:
      requests:
        cpu: 1
