nameOverride: ""
fullnameOverride: ""

server:
  replicaCount: 1

  image:
  imagePullPolicy: IfNotPresent

  security:
    enabled: true
    authority:
    audience:

  hostname:
  tlsEnabled: true

  storageAccountConnectionStringSecretName:
  storageAccountConnectionStringSecretDataKey: connectionString

  clusterConfigurationJson: "{}"

  imagePullSecrets: []
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}

storageServer:
  replicaCount: 1

  image:
  imagePullPolicy: IfNotPresent

  storageAccountConnectionStringSecretName:
  storageAccountConnectionStringSecretDataKey: connectionString

  imagePullSecrets: []
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}

db:
  usePasswordFile: true
  postgresqlDatabase: tyger

storagedb:
  usePasswordFile: true
  postgresqlDatabase: mrd-storage-server
